version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: increase
    open-pull-requests-limit: 20
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        update-types: ['major', 'minor', 'patch']

  - package-ecosystem: "github-actions"
    directory: '/'
    target-branch: 'main'
    open-pull-requests-limit: 20
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'