name: Node.js CI

on:
  push:
    branches:
        - main
        - issue-*
  pull_request:
    branches:
        - main
        - issue-*
permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x,22.x,24.x]

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: List reports directory
      run: |
        ls -la reports

    - name: Clean old reports
      run: rm -rf reports/test-results.json

    - name: List reports directory
      run: |
        ls -la reports

    - name: Start Restful E-commerce using Docker Compose
      run: docker compose -f docker-compose-ecommerce.yml up -d

    - name: Wait until API is ready
      run: npx wait-on --timeout 60000 --interval 5000 http://localhost:3004/health

    - name: Run Tests
      run: npm run test-and-generate-json-report

    - name: List reports directory
      run: |
        ls -la reports

    - name: Stop the service
      if: always()
      run: docker compose -f docker-compose-ecommerce.yml down --remove-orphans
    
    - name: Test Report
      uses: dorny/test-reporter@v3
      if: always()
      with:
          name: Test Results        
          path: ${{ github.workspace }}/reports/test-results.json
          reporter: 'mocha-json'